compressionLevel: mixed

defaultSemverRangePrefix: ^

enableGlobalCache: true

enableTimers: true

logFilters:
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

pnpMode: strict

tsEnableAutoTypes: false

yarnPath: .yarn/releases/yarn-4.9.2.cjs
